-- MySQL Script generated by MySQL Workbench
-- Tue Jun 24 20:22:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Distribuidora
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Distribuidora` ;

-- -----------------------------------------------------
-- Schema Distribuidora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Distribuidora` DEFAULT CHARACTER SET utf8 ;
USE `Distribuidora` ;

-- -----------------------------------------------------
-- Table `Distribuidora`.`Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Distribuidora`.`Fornecedor` ;

CREATE TABLE IF NOT EXISTS `Distribuidora`.`Fornecedor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cnpj` CHAR(18) NOT NULL,
  `nome_fantasia` VARCHAR(100) NOT NULL,
  `email_contato` VARCHAR(100) NOT NULL,
  `observacoes` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Distribuidora`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Distribuidora`.`Produto` ;

CREATE TABLE IF NOT EXISTS `Distribuidora`.`Produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `preco_unitario` DECIMAL(10,2) NOT NULL,
  `observacoes` TEXT NULL,
  `Fornecedor_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_Produto_Fornecedor1_idx` (`Fornecedor_id` ASC) ,
  CONSTRAINT `fk_Produto_Fornecedor1`
    FOREIGN KEY (`Fornecedor_id`)
    REFERENCES `Distribuidora`.`Fornecedor` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Distribuidora`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Distribuidora`.`Pessoa` ;

CREATE TABLE IF NOT EXISTS `Distribuidora`.`Pessoa` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `observacoes` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Distribuidora`.`Cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Distribuidora`.`Cargo` ;

CREATE TABLE IF NOT EXISTS `Distribuidora`.`Cargo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `salario_categoria` VARCHAR(100) NOT NULL,
  `nivel_hierarquia` TINYINT NOT NULL,
  `observacoes` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Distribuidora`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Distribuidora`.`Funcionario`;

CREATE TABLE IF NOT EXISTS `Distribuidora`.`Funcionario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_admissao` DATE NOT NULL,
  `matricula` VARCHAR(20) NOT NULL,
  `data_demissao` DATE NULL,
  `observacoes` TEXT NULL,
  `Pessoa_id` INT UNSIGNED NULL,  -- <- agora permite NULL
  `Cargo_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Funcionario_Pessoa1_idx` (`Pessoa_id` ASC),
  INDEX `fk_Funcionario_Cargo1_idx` (`Cargo_id` ASC),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC),
  CONSTRAINT `fk_Funcionario_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `Distribuidora`.`Pessoa` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Funcionario_Cargo1`
    FOREIGN KEY (`Cargo_id`)
    REFERENCES `Distribuidora`.`Cargo` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
)
ENGINE = InnoDB;

-- Trigger para soft delete: quando data_demissao for preenchida, Pessoa_id se torna NULL
DELIMITER $$

CREATE TRIGGER trg_funcionario_soft_delete
BEFORE UPDATE ON `Distribuidora`.`Funcionario`
FOR EACH ROW
BEGIN
  IF NEW.data_demissao IS NOT NULL AND OLD.data_demissao IS NULL THEN
    SET NEW.Pessoa_id = NULL;
  END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- Table `Distribuidora`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Distribuidora`.`Estado` ;

CREATE TABLE IF NOT EXISTS `Distribuidora`.`Estado` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Distribuidora`.`Cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Distribuidora`.`Cidade` ;

CREATE TABLE IF NOT EXISTS `Distribuidora`.`Cidade` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Estado_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_Cidade_Estado1_idx` (`Estado_id` ASC) ,
  CONSTRAINT `fk_Cidade_Estado1`
    FOREIGN KEY (`Estado_id`)
    REFERENCES `Distribuidora`.`Estado` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Distribuidora`.`Rua`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Distribuidora`.`Rua` ;

CREATE TABLE IF NOT EXISTS `Distribuidora`.`Rua` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `cep` INT NOT NULL,
  `Cidade_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_Rua_Cidade1_idx` (`Cidade_id` ASC) ,
  CONSTRAINT `fk_Rua_Cidade1`
    FOREIGN KEY (`Cidade_id`)
    REFERENCES `Distribuidora`.`Cidade` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Distribuidora`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Distribuidora`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `Distribuidora`.`Cliente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_fantasia` VARCHAR(100) NULL,
  `cnpj` CHAR(18) NULL,
  `numero_endereco` INT UNSIGNED NOT NULL,
  `Rua_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cliente_Rua1_idx` (`Rua_id` ASC) ,
  UNIQUE INDEX `CNPJ_UNIQUE` (`cnpj` ASC) ,
  CONSTRAINT `fk_Cliente_Rua1`
    FOREIGN KEY (`Rua_id`)
    REFERENCES `Distribuidora`.`Rua` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Distribuidora`.`Entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Distribuidora`.`Entrega` ;

CREATE TABLE IF NOT EXISTS `Distribuidora`.`Entrega` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero_endereco` INT UNSIGNED NOT NULL,
  `previsao_entrega` DATE NOT NULL,
  `data_entregue` TIMESTAMP,
  `status` VARCHAR(30) NOT NULL,
  `observacoes` TEXT NULL,
  `Funcionario_id` INT UNSIGNED NOT NULL,
  `Cliente_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Entrega_Funcionario1_idx` (`Funcionario_id` ASC) ,
  INDEX `fk_Entrega_Cliente1_idx` (`Cliente_id` ASC) ,
  CONSTRAINT `fk_Entrega_Funcionario1`
    FOREIGN KEY (`Funcionario_id`)
    REFERENCES `Distribuidora`.`Funcionario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Entrega_Cliente1`
    FOREIGN KEY (`Cliente_id`)
    REFERENCES `Distribuidora`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Distribuidora`.`Telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Distribuidora`.`Telefone` ;

CREATE TABLE IF NOT EXISTS `Distribuidora`.`Telefone` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('celular', 'residencial', 'comercial') NOT NULL,
  `ddd` CHAR(3) NOT NULL,
  `numero` CHAR(9) NOT NULL,
  `Pessoa_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_Telefone_Pessoa1_idx` (`Pessoa_id` ASC) ,
  CONSTRAINT `fk_Telefone_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `Distribuidora`.`Pessoa` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Distribuidora`.`EntregaProduto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Distribuidora`.`EntregaProduto` ;

CREATE TABLE IF NOT EXISTS `Distribuidora`.`EntregaProduto` (
  `Entrega_id` INT NOT NULL,
  `Produto_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `preco_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`Entrega_id`, `Produto_id`),
  INDEX `fk_Entrega_has_Produto_Produto1_idx` (`Produto_id` ASC) ,
  INDEX `fk_Entrega_has_Produto_Entrega1_idx` (`Entrega_id` ASC) ,
  CONSTRAINT `fk_Entrega_has_Produto_Entrega1`
    FOREIGN KEY (`Entrega_id`)
    REFERENCES `Distribuidora`.`Entrega` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Entrega_has_Produto_Produto1`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `Distribuidora`.`Produto` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Distribuidora`.`Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Distribuidora`.`Estoque` ;

CREATE TABLE IF NOT EXISTS `Distribuidora`.`Estoque` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantidade_atual` INT NOT NULL,
  `Produto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Estoque_Produto1_idx` (`Produto_id` ASC) ,
  UNIQUE INDEX `Produto_id_UNIQUE` (`Produto_id` ASC) ,
  CONSTRAINT `fk_Estoque_Produto1`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `Distribuidora`.`Produto` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Distribuidora`.`PessoaFornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Distribuidora`.`PessoaFornecedor` ;

CREATE TABLE IF NOT EXISTS `Distribuidora`.`PessoaFornecedor` (
  `Pessoa_id` INT UNSIGNED NOT NULL,
  `Fornecedor_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Pessoa_id`, `Fornecedor_id`),
  INDEX `fk_Pessoa_has_Fornecedor_Pessoa1_idx` (`Pessoa_id` ASC),
  INDEX `fk_Pessoa_has_Fornecedor_Fornecedor1_idx` (`Fornecedor_id` ASC),
  CONSTRAINT `fk_Pessoa_has_Fornecedor_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `Distribuidora`.`Pessoa` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pessoa_has_Fornecedor_Fornecedor1`
    FOREIGN KEY (`Fornecedor_id`)
    REFERENCES `Distribuidora`.`Fornecedor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Distribuidora`.`Pessoa_has_Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Distribuidora`.`Pessoa_has_Cliente` ;

CREATE TABLE IF NOT EXISTS `Distribuidora`.`Pessoa_has_Cliente` (
  `Pessoa_id` INT UNSIGNED NOT NULL,
  `Cliente_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Pessoa_id`, `Cliente_id`),
  INDEX `fk_Pessoa_has_Cliente_Cliente1_idx` (`Cliente_id` ASC) ,
  INDEX `fk_Pessoa_has_Cliente_Pessoa1_idx` (`Pessoa_id` ASC) ,
  CONSTRAINT `fk_Pessoa_has_Cliente_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `Distribuidora`.`Pessoa` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pessoa_has_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_id`)
    REFERENCES `Distribuidora`.`Cliente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
